name: Terraform S3 Pipeline

on:
  push:
    branches:
      - main
    paths:
      - 'infra-s3/**'
      - '.github/**'
  pull_request:
    branches:
      - main
    paths:
      - 'infra-s3/**'
      - '.github/**'

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.0

      - name: Terraform fmt
        run: terraform -chdir=infra-s3 fmt -check

      - name: Terraform init
        run: terraform -chdir=infra-s3 init -backend-config="bucket=pgr301-terraform-state-74" -backend-config="region=eu-west-1"

      - name: Terraform validate
        run: terraform -chdir=infra-s3 validate

      - name: Terraform plan
        run: terraform -chdir=infra-s3 plan -out=tfplan

      - name: Terraform apply
        if: github.ref == 'refs/heads/main'
        run: terraform -chdir=infra-s3 apply -auto-approve tfplan
